### ISSUE TITLE
Not working on Netpen MyBB theme

### ISSUE THREAD

**Issue by betaboy44** [neko/lock#3]
Hello,
I am using http://community.mybb.com/mods.php?action=view&pid=727
It's not working on it,
So hide feature is working, either Reply to view or Pay to view.
Moreover if it comes with toolbar support then it would be more nice.

Kindly help.

**Comment by clickbait** [comment]
mind describing what's wrong with it?

Also, do you have newpoints installed?

**Comment by clickbait** [comment]
@betaboy44 anything on this?

**Comment by betaboy44** [comment]
Nope nothing, no body helped :p

**Comment by clickbait** [comment]
You never replied to my questions, so I was unable to help.

**Comment by betaboy44** [comment]
Oh jesus, sorry you are module author :p 
I thought you are plugin user like me, anyway i have figured it out.

Thanks for your concern dear !

**Comment by clickbait** [comment]
Ah, alright; that's good.

Gonna close this issue now.
