### ISSUE TITLE
A fatal error with shortcodes

### ISSUE THREAD

**Issue by ladaposamuel** [neko/lock#4]
Fatal error: Cannot call method self::run_shortcode() or method does not exist in /home/a8278793/public_html/inc/plugins/lock/shortcodes.class.php on line 81

**Comment by clickbait** [comment]
What PHP version are you using?

**Comment by ladaposamuel** [comment]
5.2.*

**Comment by clickbait** [comment]
I'd recommend bumping that up to at least 5.4, support for 5.2 is long gone.

**Comment by clickbait** [comment]
Yeah, the issue's with the old version of PHP, you'll need to install a newer version or do the fix suggested here:
http://stackoverflow.com/questions/14316937/self-in-php5-2

**Comment by ladaposamuel** [comment]
working fine  now in case of future problems
**Line 81:**
`return preg_replace_callback( "/$pattern/s", 'Shortcodes::run_shortcode', $content );`
